### ISSUE TITLE
Handlers and swap directories

### ISSUE THREAD

**Issue by jza34** [CSC-IT-Center-for-Science/ansible-role-squid#1]
Hi,
I browsed your source and I want to share with you because I am also developping a role for Squid.
First why don't you use Handlers (notify) ?
Second, how do you manage creation of swap directories? Squid refuse to start until 'squid -z' is run. Do you create it manualy after your role completed?
If so I keep thinking it must be something to keep things automaticaly, that is the meaning of using tools like Ansible, don't you?
Maybe use the 'run_once' but it seems a little dangerous for me...:(
Thanks for your answer,
Sebastien

**Comment by martbhell** [comment]
Hey,  I didn't know about handlers much when I wrote this. We can change. On Centos 7 I don't have to run it. What OS are you using?

You could first run a command to check if it exists and if it doesn't -  run the -z

**Comment by martbhell** [comment]
Changed to use handlers instead. Closing issue as no reply back about the swap directory.
